name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels: ['feature', 'area/*']
  - title: '🐛 Fixes'
    labels: ['bug', 'fix']
  - title: '🧰 Maintenance'
    labels: ['chore','ci','docs']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## Changes
  $CHANGES
