name: Bug report
description: Report a problem
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    attributes: { label: What happened?, description: Steps to reproduce }
  - type: textarea
    attributes: { label: Expected, description: What did you expect to happen? }
  - type: input
    attributes: { label: URL (if page), placeholder: "https://..." }
