name: Discover MCP servers

on:
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * *"  # ежедневно 07:17 UTC

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run discover
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python tools/discover.py
          echo
          echo "Changed files:"
          git status --porcelain

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(discover): refresh servers and registry"
          branch: ${{ github.ref_name }}
