name: Deploy Pages
on:
  workflow_run:
    workflows: [ "Build Catalog Index" ]
    types: [ completed ]
permissions:
  contents: read
  actions: read        # <— ВАЖНО: нужно, чтобы забирать артефакт из другого workflow
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
