name: Stale
on:
  schedule: [{ cron: '0 3 * * *' }]
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          days-before-stale: 30
          days-before-close: 14
          stale-issue-message: "This issue is stale. Please comment to keep it open."
          stale-pr-message: "This PR is stale. Please update or comment."
          exempt-issue-labels: "pinned,roadmap"
          exempt-pr-labels: "pinned"
