name: Validate MCP Manifests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ajv-cli
        run: npm -g i ajv-cli@5

      - name: Validate manifests against schema
        run: |
          ajv validate --allow-union-types --strict=false \
            -s schema/mcp-server.schema.json \
            -d "servers/*/mcp-server.json"

      - name: Check registry format
        run: |
          test -f registry/servers.index.json
          jq type registry/servers.index.json
          jq -e 'all(.[]; has("name") and has("path") and has("category"))' registry/servers.index.json
