name: Validate MCP Catalog

on:
  push:
    branches: [ main ]
    paths:
      - 'schema/**'
      - 'servers/**'
      - '.github/workflows/validate.yml'
  pull_request:
    paths:
      - 'schema/**'
      - 'servers/**'
      - '.github/workflows/validate.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show tree (debug)
        run: |
          echo "== pwd ==" && pwd
          echo "== ls -la ==" && ls -la
          echo "== tree schema (if any) ==" && (ls -la schema || true)

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ajv-cli
        run: npm -g i ajv-cli@5

      - name: Validate manifests (skip if schema missing)
        run: |
          set -e
          if [ ! -f schema/mcp-server.schema.json ]; then
            echo "⚠️  schema/mcp-server.schema.json not found. Skipping validation."
            exit 0
          fi
          echo "✅ Found schema. Validating..."
          ajv validate --strict=false -s schema/mcp-server.schema.json -d "servers/*/mcp-server.json"
          echo "✅ All server manifests are valid."
