name: Validate MCP manifests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ajv-cli
        run: npm -g i ajv-cli@5

      - name: Validate servers against schema
        run: |
          ajv validate \
            --allow-union-types \
            -s schema/mcp-server.schema.json \
            -d "servers/*/mcp-server.json"
