name: Validate MCP Catalog

on:
  push:
    branches: [ main ]
    paths:
      - 'schema/**'
      - 'servers/**'
      - '.github/workflows/validate.yml'
  pull_request:
    paths:
      - 'schema/**'
      - 'servers/**'
      - '.github/workflows/validate.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show tree (debug)
        run: |
          echo "::group::tree"
          ls -la
          echo
          echo "---- schema ----"
          ls -la schema || true
          echo "::endgroup::"

      - name: Install ajv-cli
        run: |
          npm -g i ajv-cli@5 ajv-formats@3

      - name: Validate manifests (draft-2020-12, strict off)
        run: |
          if [ ! -f schema/mcp-server.schema.json ]; then
            echo "⚠️ schema/mcp-server.schema.json not found — skipping validation."
            exit 0
          fi
          ajv validate --spec=draft2020 --strict=false \
            -s schema/mcp-server.schema.json \
            -d "servers/*/mcp-server.json"
          echo "✅ All server manifests are valid against schema/mcp-server.schema.json"
