name: Validate MCP Catalog

on:
  push:
    paths:
      - "servers/**"
      - "schema/**"
      - ".github/workflows/validate.yml"
  pull_request:
    paths:
      - "servers/**"
      - "schema/**"
      - ".github/workflows/validate.yml"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ajv-cli
        run: npm -g i ajv-cli@5

      # Важный момент: strict включён, но union-типы мы заменили на anyOf в схеме
      - name: Validate manifests against schema
        run: |
          ajv validate --strict=true -s schema/mcp-server.schema.json -d "servers/*/mcp-server.json"
