name: Validate MCP Catalog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ajv-cli
        run: npm -g i ajv-cli@5

      - name: Validate manifests
        run: |
          ajv validate -s schema/mcp-server.schema.json -d "servers/*/mcp-server.json"
