name: Validate MCP Catalog

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ajv-cli
        run: npm -g i ajv-cli@5 ajv-formats

      - name: Validate manifests
        run: |
          set -eux
          test -f schema/mcp-server.schema.json
          ajv validate \
            -s schema/mcp-server.schema.json \
            -d "servers/*/mcp-server.json" \
            --allowUnionTypes
