name: Validate MCP Catalog

on:
  push:
    branches: [ main ]
    paths:
      - 'schema/**'
      - 'servers/**'
      - '.github/workflows/validate.yml'
  pull_request:
    paths:
      - 'schema/**'
      - 'servers/**'
      - '.github/workflows/validate.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install ajv-cli
        run: npm -g i ajv-cli@5 ajv-formats@3

      - name: Validate manifests (draft-07)
        run: |
          set -eux
          if [ ! -f schema/mcp-server.schema.json ]; then
            echo "⚠️ schema/mcp-server.schema.json not found — skipping validation."; exit 0
          fi
          ajv validate --strict=false \
            -s schema/mcp-server.schema.json \
            -d "servers/*/mcp-server.json"
