name: Validate MCP Catalog

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ajv-cli
        run: npm -g i ajv-cli@5

      - name: Validate manifests (lenient for union types)
        run: |
          set -eux
          ajv validate \
            -s schema/mcp-server.schema.json \
            -d "servers/*/mcp-server.json" \
            --allow-union-types \
            --strict=false \
            --errors=text
