name: Validate MCP Catalog

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ajv-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq & ajv-cli
        run: |
          set -eux
          sudo apt-get update -y
          sudo apt-get install -y jq
          npm -g i ajv-cli@5

      - name: Show tree
        run: |
          set -eux
          ls -la
          echo
          tree -L 3 || true

      - name: Validate manifests with AJV (strict off)
        run: |
          set -eux
          # отключаем строгие проверки, чтобы не падать на union-типах и пр.
          ajv validate \
            --strict=false \
            -s schema/mcp-server.schema.json \
            -d "servers/*/mcp-server.json"
