name: Validate MCP Catalog

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ajv-cli
        run: |
          npm -g i ajv-cli@5

      - name: Validate manifests against schema
        run: |
          ajv validate \
            -s schema/mcp-server.schema.json \
            -d "servers/*/mcp-server.json"
