name: Validate MCP Catalog

on:
  push:
    branches: [ main ]
    paths:
      - 'schema/**'
      - 'servers/**'
      - '.github/workflows/validate.yml'
  pull_request:
    paths:
      - 'schema/**'
      - 'servers/**'
      - '.github/workflows/validate.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show tree for debugging
        run: |
          set -eux
          ls -la
          echo
          ls -la schema || true
          echo
          find servers -maxdepth 2 -type f -name "mcp-server.json" -print | sort || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ajv-cli
        run: npm -g i ajv-cli@5

      - name: Validate manifests with AJV
        run: |
          set -eux
          if [ ! -f schema/mcp-server.schema.json ]; then
            echo "::error ::schema/mcp-server.schema.json not found"
            exit 1
          fi
          ajv validate --strict=false -s schema/mcp-server.schema.json -d "servers/*/mcp-server.json"

      - name: Summary
        if: ${{ success() }}
        run: |
          {
            echo "### ✅ AJV validation passed"
            echo
            echo "- Schema: \`schema/mcp-server.schema.json\`"
            echo "- Docs found:" 
            find servers -maxdepth 2 -name mcp-server.json -print | sed 's/^/- /'
          } >> "$GITHUB_STEP_SUMMARY"
