name: Validate MCP Catalog

on:
  push:
    branches: [ main ]
    paths:
      - "schema/**"
      - "servers/**"
      - ".github/workflows/validate.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "schema/**"
      - "servers/**"
      - ".github/workflows/validate.yml"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show tree (debug)
        run: |
          echo "== schema =="; find schema -maxdepth 2 -type f -print || true
          echo "== servers =="; find servers -maxdepth 2 -type f -name "mcp-server.json" -print | sort || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install ajv-cli
        run: npm -g i ajv-cli@5 ajv-formats@3

      - name: Validate (draft-07 only)
        run: |
          ajv validate --spec=draft7 --strict=false \
            -s schema/mcp-server.schema.json \
            -d "servers/*/mcp-server.json"
